name: React App Github Deploy

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar Hello world
        run: echo "Hello, world!"

      - name: Donde estoy
        run: pwd

      - name: Que hay en la carpeta
        run: ls -lah
